# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have a high-level overview of PCA, as well as some of the details of the algorithm itself, it's time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the data

- Import the data stored in the file `'foodusa.csv'` (set `index_col=0`)
- Print the first five rows of the DataFrame 

In [2]:
import pandas as pd
data = pd.read_csv('foodusa.csv',index_col=0)



In [3]:
data

Bread  Burger  Milk  Oranges  Tomatoes
City                                                 
ATLANTA         24.5    94.5  73.9     80.1      41.6
BALTIMORE       26.5    91.0  67.5     74.6      53.3
BOSTON          29.7   100.8  61.4    104.0      59.6
BUFFALO         22.8    86.6  65.3    118.4      51.2
CHICAGO         26.7    86.7  62.7    105.9      51.2
CINCINNATI      25.3   102.5  63.3     99.3      45.6
CLEVELAND       22.8    88.8  52.4    110.9      46.8
DALLAS          23.3    85.5  62.5    117.9      41.8
DETROIT         24.1    93.7  51.5    109.7      52.4
HONALULU        29.3   105.9  80.2    133.2      61.7
HOUSTON         22.3    83.6  67.8    108.6      42.4
KANSAS CITY     26.1    88.9  65.4    100.9      43.2
LOS ANGELES     26.9    89.3  56.2     82.7      38.4
MILWAUKEE       20.3    89.6  53.8    111.8      53.9
MINNEAPOLIS     24.6    92.2  51.9    106.0      50.7
NEW YORK        30.8   110.7  66.0    107.3      62.6
PHILADELPHIA    24.5    92.3  66.7     98.0      61.7
PITTSBURGH      26.2    95.4  60.2    117.1      49.3
ST LOUIS        26.5    92.4  60.8    115.1      46.2
SAN DIEGO       25.5    83.7  57.0     92.8      35.4
SAN FRANCISCO   26.3    87.1  58.3    101.8      41.5
SEATTLE         22.5    77.7  62.0     91.1      44.9
WASHINGTON DC   24.2    93.8  66.0     81.6      46.2

## Normalize the data

Next, normalize your data by subtracting the mean from each of the columns.

In [4]:
data.mean()

Bread        25.291304
Burger       91.856522
Milk         62.295652
Oranges     102.991304
Tomatoes     48.765217
dtype: float64

In [5]:
data_nor = data - data.mean()
data_nor.head()

Bread    Burger       Milk    Oranges   Tomatoes
City                                                          
ATLANTA   -0.791304  2.643478  11.604348 -22.891304  -7.165217
BALTIMORE  1.208696 -0.856522   5.204348 -28.391304   4.534783
BOSTON     4.408696  8.943478  -0.895652   1.008696  10.834783
BUFFALO   -2.491304 -5.256522   3.004348  15.408696   2.434783
CHICAGO    1.408696 -5.156522   0.404348   2.908696   2.434783

## Calculate the covariance matrix

The next step is to calculate the covariance matrix for your normalized data. 

In [9]:
import numpy as np

In [10]:
cov_mat = np.cov([data_nor['Bread'], data_nor['Burger'], data_nor['Milk'], data_nor['Oranges'], data_nor['Tomatoes']])
cov_mat

array([[  6.2844664 ,  12.91096838,   5.71905138,   1.31037549,
          7.28513834],
       [ 12.91096838,  57.07711462,  17.50752964,  22.69187747,
         36.29478261],
       [  5.71905138,  17.50752964,  48.30588933,  -0.27503953,
         13.44347826],
       [  1.31037549,  22.69187747,  -0.27503953, 202.75628458,
         38.76241107],
       [  7.28513834,  36.29478261,  13.44347826,  38.76241107,
         57.80055336]])

## Calculate the eigenvectors

Next, calculate the eigenvectors and eigenvalues for your covariance matrix. 

In [15]:
import numpy as np
eig_values, eig_vectors = np.linalg.eig(cov_mat)


In [16]:
eig_values

array([218.99867893,  91.72316894,   3.02922934,  20.81054128,
        37.66268981])

In [17]:
eig_vectors

array([[-0.02848905, -0.16532108, -0.96716354, -0.18972574,  0.02135748],
       [-0.2001224 , -0.63218494,  0.24877074, -0.65862454,  0.25420475],
       [-0.0416723 , -0.44215032,  0.03606094,  0.10765906, -0.88874949],
       [-0.93885906,  0.31435473, -0.01521357, -0.06904699, -0.12135003],
       [-0.27558389, -0.52791603, -0.03429221,  0.71684022,  0.36100184]])

## Sort the eigenvectors 

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues to determine primary components!

In [19]:
# Get the index values of the sorted eigenvalues
e_indices = np.argsort(eig_values)[::-1] 

# Sort 
eigenvectors_sorted = eig_vectors[:, e_indices]
eigenvectors_sorted

array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the data

Finally, reproject the dataset using your eigenvectors. Reproject this dataset down to 2 dimensions.

In [20]:
transformed = eigenvectors_sorted.dot(data_nor.T).T
transformed[:5]

array([[ 11.10636706,  14.73134932, -14.17203836,   1.85530932,
        -13.15196933],
       [  1.21900301,  21.44989411,  -7.19007196,  -0.14425049,
        -18.50968283],
       [-12.29365615,  -4.73286484,  -2.84276415,  -1.4535148 ,
         -5.90817824],
       [ -4.27410508,  -4.95746329,   1.5045649 ,  -0.77897224,
         15.50821919],
       [ -2.08570219,   1.77071529,   2.26283823,  -3.2304897 ,
          4.48154292]])

In [21]:
eigenvectors_sorted[:2]


array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074]])

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further applications of PCA.